export const siteMetadata = {
  siteUrl: 'https://trazy.github.io',
  title: 'Flow@Log',
  description: '끄적끄적',
  keywords: [
    '개발',
    'development',
    'blog',
    'frontend',
    'react',
    'javascript',
    'typescript',
    'nextjs',
    'vuejs',
    'angular',
    'angularjs',
    'backend',
    'nodejs',
    'express',
    'nestjs',
    'java',
    'spring',
    'c#',
    '.net',
    '.net core',
    'git',
    'docker',
    'kubernetes',
    'k8s',
    'helm',
    'linux',
    'stream',
    'async',
    'oop',
    'fp',
    'socket',
  ],
  author: {
    name: 'trazy',
    email: 'trazy@naver.com',
  },
};
